USE RESTAURANTS

CREATE TABLE Restaurants (
	ID INT PRIMARY KEY NOT NULL,
	name VARCHAR(256) NOT NULL,
	address VARCHAR(256) NOT NULL,
	description VARCHAR(256),
	picture VARCHAR(256)
)

CREATE TABLE Users (
	ID INT PRIMARY KEY	NOT NULL,
	username VARCHAR(256) NOT NULL,
	password VARCHAR(256) NOT NULL,
	email VARCHAR(256) NOT NULL,
	role VARCHAR(256) NOT NULL
)
CREATE TABLE Ratings (
	ID INT PRIMARY KEY NOT NULL,
	restaurantID INT NOT NULL,
	userID INT NOT NULL,
	serviceRating INT,
	atmosphereRating INT,
	foodQualityRating INT
)
CREATE TABLE Orders (
	ID INT PRIMARY KEY NOT NULL,
	restaurantID INT NOT NULL,
	userID INT NOT NULL,
	address VARCHAR(256) NOT NULL,
	price DECIMAL(6,2) NOT NULL DEFAULT 0
)
CREATE TABLE Comments (
	ID INT PRIMARY KEY NOT NULL,
	restaurantID INT NOT NULL,
	userID INT NOT NULL,
	content VARCHAR(256),
	time DATE
)
CREATE TABLE Foods (
	ID INT PRIMARY KEY NOT NULL,
	name VARCHAR(256) NOT NULL
)
CREATE TABLE OrdersFoods (
	orderID INT NOT NULL,
	foodID INT NOT NULL, 
	countFood INT NOT NULL DEFAULT 0
)

CREATE TABLE RestaurantsFoods (
	restaurantID INT NOT NULL,
	foodID INT NOT NULL,
	price DECIMAL(6,2) NOT NULL DEFAULT 0
)
